### ISSUE TITLE
logging does not work when link modified

### ISSUE THREAD

**Issue by breviloquencestewardesses** [AmIJesse/LinkBait#1]
hi, 

this works great, thank you. when using the logger.php file, it creates the txt-report as it should. but when I navigate to something like logger.php/random/check2-newyork-broadway, it shows the "The requested page has been removed"-page as it should, but creates no log. what should I do?

thank you for all the great work! 

all the best –
bs

**Comment by AmIJesse** [comment]
Interesting, I can't recreate the problem on my end. 

If you're making the request from the same browser without clearing cookies it will store it in the same output text file, with the new data appended to the end. I did that so you can keep track of multiple requests from the same person without having to grep through files for the same user agent or look for filenames with the same IP address. 

I didn't make that clear on the podcast or the readme though, that's my bad. I'll update the readme right away. Hopefully that's all the issue is.

As a side note (which I'll also update on the readme) if you're using the attached .htaccess file you can send a URL that looks like

https://mydomain.com/random/check2-newyork-broadway
or even
https://mydomain.com/check?loc=new-york&p=broadway 

since the PHP file will ignore all arguments passed to it.

**Comment by breviloquencestewardesses** [comment]
Ah, that's it! Thank you very much. Everything works fine. Thank you for solving that problem and closing the gap I faced for years!
